# Generated by Django 4.0.2 on 2022-04-02 15:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddictionInfo',
            fields=[
                ('aid', models.CharField(default=api.models.id_gen, max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=6)),
                ('aid', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='aid',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='postid',
            field=models.CharField(default=api.models.id_gen, max_length=6, primary_key=True, serialize=False),
        ),
    ]
