# Generated by Django 4.0.2 on 2022-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addictioninfo_useraddiction_remove_post_id_post_aid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userid',
        ),
    ]
